// Generated by CoffeeScript 1.12.7
(function() {
  var ConsumerError, ExtensionError, NonceError, OutcomeResponseError, ParameterError, SignatureError, StoreError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ConsumerError = (function(superClass) {
    extend(ConsumerError, superClass);

    function ConsumerError(message) {
      ConsumerError.__super__.constructor.call(this, message);
    }

    return ConsumerError;

  })(Error);

  ExtensionError = (function(superClass) {
    extend(ExtensionError, superClass);

    function ExtensionError(message) {
      ExtensionError.__super__.constructor.call(this, message);
    }

    return ExtensionError;

  })(Error);

  StoreError = (function(superClass) {
    extend(StoreError, superClass);

    function StoreError(message) {
      StoreError.__super__.constructor.call(this, message);
    }

    return StoreError;

  })(Error);

  ParameterError = (function(superClass) {
    extend(ParameterError, superClass);

    function ParameterError(message) {
      ParameterError.__super__.constructor.call(this, message);
    }

    return ParameterError;

  })(Error);

  SignatureError = (function(superClass) {
    extend(SignatureError, superClass);

    function SignatureError(message) {
      SignatureError.__super__.constructor.call(this, message);
    }

    return SignatureError;

  })(Error);

  NonceError = (function(superClass) {
    extend(NonceError, superClass);

    function NonceError(message) {
      NonceError.__super__.constructor.call(this, message);
    }

    return NonceError;

  })(Error);

  OutcomeResponseError = (function(superClass) {
    extend(OutcomeResponseError, superClass);

    function OutcomeResponseError(message, codeMinor) {
      this.codeMinor = codeMinor;
      OutcomeResponseError.__super__.constructor.call(this, message);
      this.message = message;
    }

    return OutcomeResponseError;

  })(Error);

  module.exports = {
    ConsumerError: ConsumerError,
    ExtensionError: ExtensionError,
    StoreError: StoreError,
    ParameterError: ParameterError,
    SignatureError: SignatureError,
    NonceError: NonceError,
    OutcomeResponseError: OutcomeResponseError
  };

}).call(this);
