// Generated by CoffeeScript 2.5.1
(function() {
  var ConsumerError, ExtensionError, NonceError, OutcomeResponseError, ParameterError, SignatureError, StoreError;

  ConsumerError = class ConsumerError extends Error {
    constructor(message) {
      super(message);
    }

  };

  ExtensionError = class ExtensionError extends Error {
    constructor(message) {
      super(message);
    }

  };

  StoreError = class StoreError extends Error {
    constructor(message) {
      super(message);
    }

  };

  ParameterError = class ParameterError extends Error {
    constructor(message) {
      super(message);
    }

  };

  SignatureError = class SignatureError extends Error {
    constructor(message) {
      super(message);
    }

  };

  NonceError = class NonceError extends Error {
    constructor(message) {
      super(message);
    }

  };

  OutcomeResponseError = class OutcomeResponseError extends Error {
    constructor(message, codeMinor) {
      super(message);
      this.codeMinor = codeMinor;
    }

  };

  module.exports = {
    ConsumerError: ConsumerError,
    ExtensionError: ExtensionError,
    StoreError: StoreError,
    ParameterError: ParameterError,
    SignatureError: SignatureError,
    NonceError: NonceError,
    OutcomeResponseError: OutcomeResponseError
  };

}).call(this);
